### ISSUE TITLE
md5sum behaviour with older coreutils

### ISSUE THREAD

**Issue by kilicomu** [LiamBindle/bashdatacatalog#3]
Hi Liam!

Just tried running the `bashdatacatalog-selftest` and got some `md5sum` error messages:

```
md5sum: invalid option -- 's'
Try 'md5sum --help' for more information.`
```

I had a quick look and on my system this is because the `coreutils` that ships with the Linux distro is 8.22 (CentOS 7 - end of life in 2024 so still some life left in it yet!) and there is no `--ignore-missing` option to `md5sum`. The command errors out with a missing option, so anything that uses `md5sum` in `bashdatacalog` will fail.

I guess this is a 'my system' problem, but worth being aware of, as anybody else running with an older version of coreutils will see the same issue. I'll see how things go dropping that option from the command!

**Comment by LiamBindle** [comment]
Thanks for pointing this out @kilicomu! Let me know if there's anything else.
